version: '3'

services:
  calculator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py
      - ./templates:/app/templates
      - ./static:/app/static
    stdin_open: true
    tty: true

